site_name: VargaLABS
site_url: https://steven-varga.ca
site_description: Advanced Systems for Trading, Cryptography, and Data Engineering
site_author: Steven Varga
copyright: Steven Varga
docs_dir: docs
twitter_handle: "@vargaconsulting"
nav:
  - Introduction: index.md
  - Presentations: site/talks.md  
  - Projects:
    - IEX Download: site/iexdownload.md
    - IEX2H5: site/iex2h5.md
    - Radix64: site/radix64.md
    - TinyCrypto: site/tinycrypto.md
    - H5CPP header only: site/h5cpp.md
    - H5CPP compiler: site/h5cpp-compiler.md
    - Decimal Float C++: site/decimalfloat-cpp.md
    - Decimal Float Python: site/decimalfloat-python.md
    - OpenSSL++: site/openssl.md
    - BIP: site/bip.md
    - EIP: site/eip712.md
    - Generics C++: site/generics.md
    - KMS: site/kms.md
    - NSS: site/nss.md
    - Orderbook: site/orderbook.md
    - UDS: site/uds.md
  - Blog: 
      - Index: blog/index.md
plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      categories: true
      categories_name: Categories
      categories_url_format: "{slug}"
      categories_toc: true
      archive: true
      archive_name: Posts
      archive_date_format: MMMM yyyy
      archive_url_format: "{date}"
      archive_toc: true
      post_url_format: "{slug}"
      post_url_max_categories: 2      
      post_readtime: true
      post_readtime_words_per_minute: 60
  # rss: <- do not use, we have custom script: scripts/rss-build-feed.py
theme:
  name: material
  custom_dir: docs/overrides
  features:
    #- navigation.instant #<- messes up mathjax, keep it disabled!
    - search.suggest
    - content.code.copy
    - content.tooltips    
  icon:
  admonition:
  palette:
    - scheme: solarized
      primary: orange
      toggle:
        icon: moon
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: sun
        name: Switch to light mode
extra:
  social:
    - icon: material/whatsapp
      link: https://wa.me/16475611829
    - icon: material/email-fast
      link: mailto:steven@vargaconsulting.ca
    - icon: material/twitter
      link: https://x.com/vargaconsulting
    - icon: material/linkedin
      link: https://www.linkedin.com/in/steven-varga-04224a19/
    - icon: material/github 
      link: https://github.com/vargaconsulting

  analytics:
    provider: google
    property: G-L58Z6SZ3TN
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.snippets:
      base_path:
        - docs/blog/specs
        - docs/blog/examples
        - docs/blog/posts
        - docs/blog/pics
        - docs/blog/data
        - docs/blog/scripts
        - docs/blog/casts
  
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.tailwindcss.com 
  - javascripts/tw-config.js   
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.js
  - https://unpkg.com/alpinejs@3.14.9/dist/cdn.min.js
  - https://unpkg.com/@popperjs/core@2
  - https://unpkg.com/tippy.js@6

extra_css:
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.css
  - https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  - styles/custom.css
  - styles/mobile.css
  - styles/socials.css  
  - styles/background.css
  - styles/blog.css
  - styles/asciinema.css
