site_name: VARGA CONSULTING
docs_dir: docs
nav:
  - Introduction: index.md
  - Presentations: site/talks.md  
  - Projects:
    - IEX2H5: site/iex2h5.md
    - Radix64: site/radix64.md
    - TinyCrypto: site/tinycrypto.md
    - H5CPP header only: site/h5cpp.md
    - H5CPP compiler: site/h5cpp-compiler.md
    - Decimal Float C++: site/decimalfloat-cpp.md
    - Decimal Float Python: site/decimalfloat-python.md
    - IEX Download: site/iexdownload.md
    - OpenSSL++: site/openssl.md
    - BIP: site/bip.md
    - EIP: site/eip712.md
    - Generics C++: site/generics.md
    - KMS: site/kms.md
    - NSS: site/nss.md
    - Orderbook: site/orderbook.md
    - UDS: site/uds.md
  - Blog: blog/index.md
plugins:
  - search
  - blog:
      blog_dir: blog
      categories: true
      pagination_per_page: 10

theme:
  name: material
  custom_dir: docs/overrides
  highlightjs: true
  features:
    #- navigation.instant <- messes up mathjax, keep it disabled!
    - search.suggest
    - content.code.copy
    - content.tooltips    
  icon:
  admonition:
  palette:
    - scheme: solarized
      primary: orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
extra:
  social:
    - icon: material/whatsapp
      link: https://wa.me/16475611829
    - icon: material/email-fast
      link: mailto:steven@vargaconsulting.ca
    - icon: material/twitter
      link: https://x.com/vargaconsulting
    - icon: material/linkedin
      link: https://www.linkedin.com/in/steven-varga-04224a19/
    - icon: material/github 
      link: https://github.com/vargaconsulting
    - icon: simple/discord
      link: https://discord.gg/rZHgg2HpsD

  icons:
    - material
    - fontawesome/brands
    - fontawesome/solid
    
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.critic
  - pymdownx.keys
    
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.js
  - javascripts/mathjax.js

extra_css:
  - styles/custom.css
  - styles/background.css
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.0.1/dist/bundle/asciinema-player.css
