<script>
  document.addEventListener("DOMContentLoaded", function () {
    function waitForAsciinemaPlayer(attempts = 10) {
      if (typeof AsciinemaPlayer !== "undefined") {
        AsciinemaPlayer.create('/blog/casts/iex-termshark.cast', document.getElementById('asciicast-iex-termshark'), {
          cols: 120, rows: 30, autoPlay: true,  loop: false, speed: 1.3,  idleTimeLimit: .5, controls: true
        });
      } else if (attempts > 0) {
        setTimeout(() => waitForAsciinemaPlayer(attempts - 1), 200);
      } else {
        console.error("AsciinemaPlayer failed to load.");
      }
    }
    waitForAsciinemaPlayer();
});
</script>
